# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0-focal AS build
WORKDIR /source
COPY ..
RUN dotnet restore "./BlogAPI/BlogAPI.csproj" --disable-parallel
RUN dotnet publish "./BlogAPI/BlogAPI.csproj" -c release -o /app --no-restore

# Serve Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0-focal
WORKDIR /app
COPY --from=build /app ./

EXPOSE 5000

ENTRYPOINT ["dotnet", "BlogAPI.dll"]
